services:
  api:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
    environment:
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=TRUE # Stuff printed to logs are visible immediately
    entrypoint: >
      gunicorn 
      --chdir /app app:app -w 1 
      --threads 1 -b 0.0.0.0:8080
      --timeout 120 
      --reload
