services:
  api:
    build: ./api
    ports:
      - "5000:5000"
    volumes:
      - ./api/app.py:/app/app.py
      - ./api/.env:/app/.env
    environment:
      - FLASK_ENV=development
      - TORCHSERVE_URL=http://torchserve:8080
    depends_on:
      - torchserve

  torchserve:
    image: pytorch/torchserve:latest
    ports:
      - "8080:8080"  # inference API
      - "8081:8081"  # management API
    volumes:
      - ./model_store:/home/model-server/model-store
      - ./torchserve_config.properties:/home/model-server/config.properties
    command: >
      torchserve --start 
      --model-store model-store 
      --ts-config /home/model-server/config.properties
    environment:
      - TS_MAX_RESPONSE_SIZE=6553600
      - TS_MAX_REQUEST_SIZE=6553600
      - TS_NO_TOKEN_REQUIRED=true
      - ENABLE_TORCH_PROFILER=true
      - ENABLE_AUTH_TOKEN=false
      - TOKEN_REQUIRED=false

  test:
    build: ./webapp
    volumes:
      - ./webapp:/app
    depends_on:
      - api 