
services:
  api:
    build: ./api
    ports:
      - "5000:5000"
    volumes:
      - ./api:/app
    environment:
      - FLASK_ENV=development
      - TORCHSERVE_URL=http://torchserve:8080
    depends_on:
      - torchserve

  torchserve:
    image: pytorch/torchserve:latest
    ports:
      - "8080:8080"  # inference API
      - "8081:8081"  # management API
    volumes:
      - ./model_store:/home/model-server/model-store
    command: torchserve --start --model-store model-store --models all
    environment:
      - TS_MAX_RESPONSE_SIZE=65536
      - TS_MAX_REQUEST_SIZE=65536 