services:
  api:
    build: ./api
    ports:
      - "5000:5000"
    volumes:
      - ./api:/app
    environment:
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=TRUE # Stuff printed to logs are visible immediately
    entrypoint: >
      gunicorn 
      --chdir /app app:app -w 1 
      --threads 1 -b 0.0.0.0:5000
      --timeout 120 
      --reload
