services:
  api:
    build: ./api
    ports:
      - "5000:5000"
    volumes:
      - ./api:/app
    environment:
      - FLASK_ENV=development


  app:
    build: ./webapp
    ports:
      - "3000:3000"
    volumes:
      - ./webapp:/app
    depends_on:
      - api 